// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DocumentsController from "./documents_controller"
application.register("documents", DocumentsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UploaderController from "./uploader_controller"
application.register("uploader", UploaderController)
