default: &default
  adapter: postgresql
  encoding: unicode
  username: pankajroy
  password: Pankajroy@01
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: awslearning_development

test:
  <<: *default
  database: awslearning_test

production:
  <<: *default
  database: awslearning_production
  username: pankajroy
  password: <%= Rails.application.credentials.dig(:database, :pg_password) %>